<?php

namespace ConfigBundle\Repository;

/**
 * ConfigAgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigAgenceRepository extends \Doctrine\ORM\EntityRepository
{
}
